import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import TokenHeader from '../components/TokenHeader'
import HomeBanner from '../components/HomeBanner'
import TokenServices from '../components/TokenServices'
import AboutWe from '../components/AboutWe'
import BannerTech from '../components/BannerTech'
import TokenInfo from '../components/TokenInfo'
import Customers from '../components/Customers'
import ContactSimple from '../components/ContactSimple'
import TokenFooter from '../components/TokenFooter'
import MenuToken from '../components/MenuToken'
import { useSelector } from 'react-redux'
import BannerReutilizable from '../components/BannerReutilizable';

const Web = () => {
    const showMenu = useSelector(state => state.app.showMenu);

    return (
        <section className='container-tokenweb'>
            <Head>
                <title>Servicios de diseño web</title>
                {/* <meta name="description" content="Generated by create next app" /> */}
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                showMenu && (
                <MenuToken />
                )
            }
            <TokenHeader />
            <BannerReutilizable
                title="Consigue una presencia online impresionante con nuestro diseño web profesional"
                subtitle="Mejora la imagen de tu negocio y atrae a más clientes con nuestro diseño web personalizado y de alta calidad"
                ctaLink=""
                ctaText="Comienza hoy"
                background="https://www.bigbuy.eu/psublic/img/landings/dropshipping-technology/technology-banner.jpg"
            />
            <ContactSimple />
            <TokenFooter />
        </section>
    );
};

export default Web;